### ISSUE TITLE
This repository is in violation of Unity Asset Store's terms.

### ISSUE THREAD

**Issue by EnoxSoftware** [mcmorris/ahsar#1]
Hi.
I am a developer of "OpenCVForUnity".
Your public repository contains the files of the paid Unity asset that I am selling in the asset store.
Could you add the "OpenCVForUnity" folder to the .ignore file or change the attribute of the repository to private?
I hope that you will understand.
Thank you in advance.

Enox Software

**Comment by mcmorris** [comment]
Hi Enox,

I’m sorry about that!  Of course I’ll modify the OpenCVForUnity folder to .ignore, and remove the existing files from the repo.

There were problems with our original repo setup and I had assumed my team had not shared any files from your work that would circumvent Unity store protections.

I am currently away from my computer - I’ll try making the changes over mobile, but worst case scenario, I can have things resolved before the end of this Sunday (that is to say, within 48 hours of this email).

Sincerely,
-Michael

**Comment by mcmorris** [comment]
Hi Enox,

Alright, I've added the data to the git.ignore file, and removed all OpenCV files from the repo as of the latest push today (18/03/2018, at 1:00am MST).

I don't think I missed anything, but can you please confirm that all offending files have been removed from this repo?

**Comment by EnoxSoftware** [comment]
Thank you for your quick and polite response.

**Comment by mcmorris** [comment]
You're very welcome.

**Comment by mcmorris** [comment]
Closing issue now that offending files are removed and the repo is back in compliance with TOS.

**Comment by EnoxSoftware** [comment]
Hi Michael.

Thank you for your quick response the other day.
I noticed that the asset files remained included in past commits in your repository.
Could you delete the files completely using the "git filter - branch" command, etc?

Thank you in advance.

Enox Software

**Comment by mcmorris** [comment]
Hi Enox,

You're very welcome, sorry for the trouble!

I just ran a git filter-branch, and thought everything was clear, but it doesn't seem to have stuck.  I'll look into the issue some more (maybe my file pattern was bad).

**Comment by mcmorris** [comment]
Okay, I've cleared the repo history as best I can.  If there are still problems, let me know, and I'll wipe the repo entirely and create a new repo with no history of the sensitive files.  Thanks!

**Comment by EnoxSoftware** [comment]
Thank you for your quick response.
It seems that the files is completely deleted as far as I see.

**Comment by mcmorris** [comment]
Great, thank you!  I'm glad I was able to get this corrected for you.
